# Module_test
matrix:
  include:    
    - language: c  
      sudo: false # only for faster builds  
      compiler:
        - gcc
      script:  
        - gcc -o Collision Collision.c 
        - ./Collision
        
